# Generated by Django 4.0.2 on 2022-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic', models.CharField(max_length=100, unique=True)),
                ('strength', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
