# Generated by Django 4.0.2 on 2022-02-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('generic',), 'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
    ]
