# Generated by Django 4.0.2 on 2022-02-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_id_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
