# Generated by Django 4.0.2 on 2022-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_generic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
