# Generated by Django 4.0.2 on 2022-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_generic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
