# Generated by Django 4.0.2 on 2022-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
